=== api-evangelist/f5-networks/json-schema/bigip-icontrol-rest-virtual-server-update-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "VirtualServerUpdate",
  "type": "object",
  "description": "Request body for updating a virtual server.",
  "properties": {
    "description": {
      "type": "string"
    },
    "destination": {
      "type": "string"
    },
    "ipProtocol": {
      "type": "string"
    },
    "mask": {
      "type": "string"
    },
    "pool": {
      "type": "string"
    },
    "profiles": {
      "type": "array"
    },
    "persist": {
      "type": "array"
    },
    "source": {
      "type": "string"
    },
    "sourcePort": {
      "type": "string"
    },
    "translateAddress": {
      "type": "string"
    },
    "translatePort": {
      "type": "string"
    },
    "connectionLimit": {
      "type": "integer"
    },
    "enabled": {
      "type": "boolean"
    },
    "disabled": {
      "type": "boolean"
    },
    "mirror": {
      "type": "string"
    },
    "rateLimit": {
      "type": "string"
    },
    "rules": {
      "type": "array"
    },
    "vlans": {
      "type": "array"
    },
    "vlansEnabled": {
      "type": "boolean"
    },
    "vlansDisabled": {
      "type": "boolean"
    },
    "fallbackPersistence": {
      "type": "string"
    }
  }
}

=== api-evangelist/f5-networks/examples/bigip-icontrol-rest-virtual-server-update-example.json
{
  "description": "A sample description.",
  "destination": "example_value",
  "ipProtocol": "example_value",
  "mask": "example_value",
  "pool": "example_value",
  "profiles": [],
  "persist": [],
  "source": "example_value",
  "sourcePort": "example_value",
  "translateAddress": "example_value",
  "translatePort": "example_value",
  "connectionLimit": 10,
  "enabled": true,
  "disabled": true,
  "mirror": "example_value",
  "rateLimit": "example_value",
  "rules": [],
  "vlans": [],
  "vlansEnabled": true,
  "vlansDisabled": true,
  "fallbackPersistence": "example_value"
}
